export const treats = [
    {
      name: "Chritsmas Cupcakes",
      picture: "https://i.imgur.com/GTTzhg7.jpg",
      height: "35px",
      width: "35px",
      description:
        "Our fresh, moist cake is formed into small spheres, before being given a delicious coating of chocolate. They are attached to lollipop sticks and are hand decorated.",
      price: 5.85,
    },
  
    {
      name: "Dessert's cup(cookies and cream",
      picture: "https://i.imgur.com/N94vN9T.png",
      height: "35px",
      width: "35px",
      description:
        "Our fresh, moist cake is formed into small spheres, before being given a delicious coating of chocolate. They are attached to lollipop sticks and are hand decorated.",
      price: 5.85,
    },
    {
      name: "Party Platter",
      picture: "https://i.imgur.com/GoIk2RL.jpg",
      height: "35px",
      width: "35px",
      description:
        "Our fresh, moist cake is formed into small spheres, before being given a delicious coating of chocolate. They are attached to lollipop sticks and are hand decorated.",
      price: 5.85,
    },
    {
      name: "To Die for Cookies",
      picture: "https://i.imgur.com/9DFZMok.jpg",
      height: "35px",
      width: "35px",
      description: "",
      price: 5.85,
    },
  
    {
      name: "Special Birthday Breakfast",
      picture: "https://i.imgur.com/uEiTv6o.jpg",
      height: "35px",
      width: "35px",
      description:
        "Our fresh, moist cake is formed into small spheres, before being given a delicious coating of chocolate. They are attached to lollipop sticks and are hand decorated.",
      price: 5.85,
    },
    {
      name: "Chocolate Dipped Strawberries",
      picture: "https://i.imgur.com/5NghbJ4.jpg",
      height: "35px",
      width: "35px",
      description: "",
      price: 5.85,
    },
    {
      name: "Mini Pancakes",
      picture: "https://i.imgur.com/KMcet4y.png",
      height: "35px",
      width: "35px",
      description: "",
      price: 5.85,
    },
    {
      id: "8",
      name: "CakesPop Popsicles",
      picture: "https://i.imgur.com/TqFcQ7O.png",
      height: "35px",
      width: "35px",
      description: "",
      price: 5.85,
    },
    {
      id: "9",
      name: "Cinnamon Trees",
      picture: "https://i.imgur.com/rQym012.jpg",
      height: "35px",
      width: "35px",
      description: "",
      price: 5.85,
    },
  
    {
      id: "10",
      name: "Cheesecake cup",
      picture: "https://i.imgur.com/7K7PaBZ.jpg",
      height: "35px",
      width: "35px",
      description: "",
      price: 5.85,
    },
    {
      id: "11",
      name: "Guava Pastries",
      picture: "https://i.imgur.com/ZM3GHzp.jpg",
      height: "35px",
      width: "35px",
      description: "",
      price: 5.85,
    },
    {
      id: "12",
      name: "Special Treat",
      picture: "https://i.imgur.com/rXoSWlz.jpg",
      height: "35px",
      width: "35px",
      description: "",
      price: 5.85,
    },
    {
      id: "13",
      name: "Custom Cupcakes",
      picture: "https://i.imgur.com/ueYkb1r.jpg",
      height: "35px",
      width: "35px",
      description:
        "Our fresh, moist cake is formed into small spheres, before being given a delicious coating of chocolate. They are attached to lollipop sticks and are hand decorated.",
      price: 5.85,
    },
    {
      id: "13",
      name: "Cheesecake cups",
      picture: "https://i.imgur.com/QRv4kom.jpg",
      height: "35px",
      width: "35px",
      description:
        "Our fresh, moist cake is formed into small spheres, before being given a delicious coating of chocolate. They are attached to lollipop sticks and are hand decorated.",
      price: 5.85,
    },
    {
      id: "13",
      name: "Special Event Gift",
      picture: "https://i.imgur.com/9554tty.jpg",
      height: "35px",
      width: "35px",
      description:
        "Our fresh, moist cake is formed into small spheres, before being given a delicious coating of chocolate. They are attached to lollipop sticks and are hand decorated.",
      price: 5.85,
    },
    {
      id: "13",
      name: "Custom Theme Lollipops",
      picture: "https://i.imgur.com/tQR3tCL.jpg",
      height: "35px",
      width: "35px",
      description:
        "Our fresh, moist cake is formed into small spheres, before being given a delicious coating of chocolate. They are attached to lollipop sticks and are hand decorated.",
      price: 5.85,
    },
    {
      id: "13",
      name: "Cream filled cupcakes",
      picture: "https://i.imgur.com/kABw4SY.jpg",
      height: "35px",
      width: "35px",
      description:
        "Our fresh, moist cake is formed into small spheres, before being given a delicious coating of chocolate. They are attached to lollipop sticks and are hand decorated.",
      price: 5.85,
    },
    {
      id: "13",
      name: "Mixed platter",
      picture: "https://i.imgur.com/nFvp7Gb.jpg",
      height: "35px",
      width: "35px",
      description:
        "Our fresh, moist cake is formed into small spheres, before being given a delicious coating of chocolate. They are attached to lollipop sticks and are hand decorated.",
      price: 5.85,
    },
  ];
  
  export const size = ["round", "square", "heart-shape", "rectangular", "custom"];
  export const filling = [
    "frosting",
    "custard",
    "whipped cream ",
    "chocolate",
    "vanilla",
    "buttercream",
    "oreos",
    "cookies",
  ];
  export const flavour = [
    "red velvet",
    "confetti",
    "chocolate",
    "vanilla",
    "strawberry",
    "coconut",
    "guava",
    "creamy milk(dulce leche)",
  ];
  // export const type = [];
  
  export const Ocassion = [
    `New Year's Day 🎉`,
    `Valentine's Day 💖`,
    `St. Patrick's Day ☘️`,
    "Easter 🐰",
    `Mother's Day 💐`,
    `Father's Day 👨`,
    "Indepependence Day 🇺🇸 ",
    "Halloween 🎃 ",
    "Thanksgiving 🦃",
    "Christmas 🎄",
    "Birthday 🎂",
  ];
  let description = `Freshly customizable treat for special celebration on ${Ocassion[1]}`;
  
  export const cakes = [
    {
      name: `Custom Sports Birthday's Cake`,
      picture: "https://i.imgur.com/tjjG4os.jpg",
      Ocassion: Ocassion,
      size: size,
      flavour: flavour,
      filling: filling,
      price: 32.99,
    },
    {
      name: `Custom Valentine's Cake`,
      picture: "https://i.imgur.com/qoSSo5G.png",
      Ocassion: Ocassion,
      size: size,
      flavour: flavour,
      filling: filling,
      price: 32.99,
    },
    {
      name: `Gender Reveal Cake`,
      picture: "https://i.imgur.com/ELdPnTr.jpg",
      size: size,
      flavour: flavour,
      filling: filling,
      price: 32.99,
    },
    {
      name: ` 1 Year Old Smash Cake`,
      picture: "https://i.imgur.com/3oC981N.png",
      size: size,
      flavour: flavour,
      filling: filling,
      price: 32.99,
    },
    {
      name: `Mother's Day Cake`,
      picture: "https://i.imgur.com/vsfA4N8.jpg",
      size: size,
      flavour: flavour,
      filling: filling,
      price: 32.99,
    },
    {
      name: `Naked Red Velvet Cake`,
      picture: "https://i.imgur.com/BlOlu1M.jpg",
      size: size,
      flavour: flavour,
      filling: filling,
      price: 32.99,
    },
  
    {
      name: `Custom Birthday's Cake`,
      picture: "https://i.imgur.com/BBl0nli.jpg",
      Ocassion: Ocassion,
      size: size,
      flavour: flavour,
      filling: filling,
      price: 32.99,
    },
    {
      name: ` Birthday Cake`,
      picture: "https://i.imgur.com/fOKSsQx.png",
      size: size,
      flavour: flavour,
      filling: filling,
      price: 32.99,
    },
    {
      name: `Cream filled Red Velvet`,
      picture: "https://i.imgur.com/vsFeyL0.jpg",
      size: size,
      flavour: flavour,
      filling: filling,
      price: 32.99,
    },
    {
      name: `Chocolate Cake`,
      picture: "https://i.imgur.com/iYOXcSx.jpg",
      size: size,
      flavour: flavour,
      filling: filling,
      price: 32.99,
    },
    {
      name: `Fruits Cake`,
      picture: "https://i.imgur.com/7rA0Eba.jpg",
      size: size,
      flavour: flavour,
      filling: filling,
      price: 32.99,
    },
    {
      name: `Customs Special Ocassion Cakes`,
      picture: "https://i.imgur.com/vBCDE08.jpg",
      size: size,
      flavour: flavour,
      filling: filling,
      price: 32.99,
    },
  ];
  